---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: cloudflare-tunnel
  namespace: argocd
spec:
  syncPolicy: 
    preserveResourcesOnDeletion: true
  generators:
    - list:
        elements:
          - cluster: oci-cluster
  template:
    metadata:
      name: "cloudflare-tunnel-{{cluster}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/leonhrt/oci-kubernetes
        targetRevision: HEAD
        path: "cloudflare-tunnel/overlays/{{cluster}}"
      destination:
        name: "{{cluster}}"
        namespace: cloudflare-tunnel
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
