---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare-tunnel
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: cloudflare-tunnel-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: ocid1.vaultsecret.oc1.eu-frankfurt-1.amaaaaaaaelrjyqavwowruktchtycofselzuygldrfxtf4qtfbfyma6jgygq
